version: '3.5'

services:
  postgres:
    container_name: keddit_postgres
    image: postgres:15-alpine
    environment:
      # Real environments should not use default values
      POSTGRES_USER: ${POSTGRES_USER:-keddit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-kita}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres:
